git submodule add http://g.hiddens.link:8929/99players.io/projects/99-party-3d/modules/external.git "Assets/External"
git submodule add http://g.hiddens.link:8929/99players.io/projects/99-party-3d/modules/plugins.git "Assets/Plugins"
git submodule add http://g.hiddens.link:8929/99players.io/projects/99-party-3d/modules/standard-assets.git "Assets/Standard Assets"
git submodule add http://g.hiddens.link:8929/99players.io/projects/99-party-3d/modules/textmesh-pro.git "Assets/TextMesh Pro"
git submodule add http://g.hiddens.link:8929/99players.io/projects/99-party-3d/modules/framework.git "Assets/99Players/Framework"
git submodule add http://g.hiddens.link:8929/99players.io/projects/99-party-3d/modules/data.git "Assets/99Players/Data"
git submodule add http://g.hiddens.link:8929/99players.io/projects/99-party-3d/modules/data-2d.git "Assets/99Players/Data2D"
git submodule add http://g.hiddens.link:8929/99players.io/projects/99-party-3d/modules/projectsettings "ProjectSettings"
git submodule add http://g.hiddens.link:8929/99players.io/projects/99-party-3d/modules/packages "Packages"